blog_django/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.post_list,name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<str:slug>',views.post_detail,name='post_detail'),
    path('tag/<str:tag_slug>',views.post_list,name='post_list_by_tag'),
]

blog_django/blog_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog_django/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class Tag(models.Model):
    title = models.CharField(max_length=250)
    
    def __str__(self):
        return self.title
class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft')
    tag_name = models.ManyToManyField(Tag)

    def get_tags(self):
        return ",".join([p.title for p in self.tag_name.all()])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ]
        )
    



class Comment(models.Model):

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments')
    username = models.CharField(max_length=120)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.username, self.post)

blog_django/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('username', 'email','body')

blog_django/blog/views.py
from turtle import title
from django.shortcuts import render
from .forms import CommentForm
# Create your views here.
from .models import Post,Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def post_list(request,tag_slug=None):
    if tag_slug:
        tag = Tag.objects.filter(title=tag_slug).first()
        posts_list =  Post.objects.filter(tag_name__in=[tag])
    else:
        posts_list =  Post.objects.all()
    tag_list = Tag.objects.all()
    paginator = Paginator(posts_list, 3)
    page = request.GET.get('page')  # 获取页码
    try:
        posts = paginator.page(page)  # 获取某页对应的记录
    except PageNotAnInteger:  # 如果页码不是个整数
        posts = paginator.page(1)  # 取第一页的记录
    except EmptyPage:  # 如果页码太大，没有相应的记录
        posts = paginator.page(paginator.num_pages)  # 取最后一页的记录
    return render(request,'blog/post/list.html',locals())


def post_detail(request,year,month,day,slug):
    post =  Post.objects.filter(
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug
    ).first()

        # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,'blog/post/detail.html',locals())

blog_django/blog/templates/blog/post/detail.html
{% block content %}

<h2>{{ post.title }}</h2>
<p>
    Published {{ post.publish }} by {{ post.auther }}
</p>
    {{post.body|linebreaks}}
    {% with comments.count as total_comments %}
    <h2>
    {{ total_comments }} comment{{total_comments|pluralize}}
    </h2>
    {% endwith %}
    {% for comment in post.comments.all %} 
    <div>
    <p>
    Comment by {{ comment.username }}  {{ comment.created }}
    </p>
    {{ comment.body| linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
    {% endfor %}


    {% if new_comment %}
    <h2>Your comment has been added.</h2>
    {% else %}
    <h3><a name="commentform"></a>Leave a Comment</h3>
    <form action="#commentform" method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
    {% endif %}

    {% endblock %}

blog_django/blog/templates/blog/post/list.html
{% block content %}
<h1>My blog</h1>
{% for post in posts %}
<a href="{{ post.get_url }}">
  <h2>{{ post.title }}</h2>
</a>

<p>

  Published {{ post.publish }} by {{ post.auther }}
</p>
<p>
  Tags:
  {% for tag in post.tag_name.all %}
  <a href="{% url 'blog:post_list_by_tag' tag.title %}">{{ tag.title }}</a>
  {% if not forloop.last %}, {% endif %}

  {% endfor %}
</p>

{{post.body|truncatechars:5 }}

{% endfor %}

<p>


  {% for page_number in posts.paginator.page_range %}
  {% if page_number == posts.number %}
  {{ page_number }}
  {% else %}
  <a href="?page={{ page_number }}">{{ page_number }}</a>
  {% endif %}
  {% endfor %}
</p>

<hr>

<div>
{% for tag in tag_list %}
<a href="{% url 'blog:post_list_by_tag' tag.title %}">{{ tag.title }}</a>
{{ tag.post_set.count }}
{% endfor %}

</div>

{% endblock %}